# docker-compose.yml - Ambiente local para testes e desenvolvimento

version: '3.8'

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=enem-cluster
      - HDFS_CONF_dfs_permissions=false
    ports:
      - "9870:9870"
      - "9000:9000"
      - "8020:8020"
    volumes:
      - hdfs-namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=enem-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hdfs-datanode:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION=no
      - SPARK_RPC_ENCRYPTION=no
      - SPARK_SUBMIT_OPTIONS=--conf spark.jars.ivy=/tmp/.ivy2
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - hadoop
    depends_on:
      - namenode

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_SUBMIT_OPTIONS=--conf spark.jars.ivy=/tmp/.ivy2
    networks:
      - hadoop
    depends_on:
      - spark-master

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - hadoop
    depends_on:
      - spark-master
      - datanode

volumes:
  hdfs-namenode:
  hdfs-datanode:

networks:
  hadoop:
    driver: bridge